import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const iconsDir = path.join(root, 'node_modules', 'lucide', 'dist', 'esm', 'icons');

const searchPaths = [
  path.join(root, 'web'),
  path.join(root, 'src'),
];

const iconNames = new Set();
for (const dir of searchPaths) {
  const entries = fs.readdirSync(dir, { recursive: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry);
    if (!fs.statSync(fullPath).isFile()) continue;
    if (!entry.endsWith('.html') && !entry.endsWith('.ts')) continue;
    const content = fs.readFileSync(fullPath, 'utf-8');
    const matches = content.matchAll(/data-lucide="([^"]+)"/g);
    for (const m of matches) {
      iconNames.add(m[1]);
    }
  }
}

const icons = {};
for (const name of iconNames) {
  const filePath = path.join(iconsDir, `${name}.mjs`);
  if (!fs.existsSync(filePath)) {
    console.warn(`Warning: icon "${name}" not found`);
    continue;
  }
  const content = fs.readFileSync(filePath, 'utf-8');
  const match = content.match(/const \w+\s*=\s*(\[[\s\S]*?\]);\n\nexport/);
  if (!match) {
    console.warn(`Warning: could not parse icon "${name}"`);
    continue;
  }
  icons[name] = eval('(' + match[1] + ')');
}

const iconDataJSON = JSON.stringify(icons);
const distDir = path.join(root, 'dist');
fs.mkdirSync(distDir, { recursive: true });

const output = `/* Generated by build-icons.mjs — do not edit */
/* Icons derived from Lucide (ISC) — https://lucide.dev */
/* Some icons derived from Feather (MIT) — https://feathericons.com */
/* Copyright (c) 2026 Lucide Icons and Contributors */
(function(){
  var icons = ${iconDataJSON};
  function createSVGNode(def) {
    var el = document.createElementNS('http://www.w3.org/2000/svg', def[0]);
    var attrs = def[1];
    for (var key in attrs) el.setAttribute(key, attrs[key]);
    var children = def[2];
    if (children) {
      for (var i = 0; i < children.length; i++) {
        el.appendChild(createSVGNode(children[i]));
      }
    }
    return el;
  }
  window.replaceIcons = function(opts) {
    var size = (opts && opts.size) || 24;
    var els = document.querySelectorAll('[data-lucide]');
    for (var i = 0; i < els.length; i++) {
      var el = els[i];
      var name = el.getAttribute('data-lucide');
      var icon = icons[name];
      if (!icon) continue;
      var elAttrs = {};
      for (var j = 0; j < el.attributes.length; j++) {
        var a = el.attributes[j];
        elAttrs[a.name] = a.value;
      }
      var hasA11y = elAttrs['aria-label'] || elAttrs['aria-labelledby'];
      var svgAttrs = {
        xmlns: 'http://www.w3.org/2000/svg',
        width: size,
        height: size,
        viewBox: '0 0 24 24',
        fill: 'none',
        stroke: 'currentColor',
        'stroke-width': 2,
        'stroke-linecap': 'round',
        'stroke-linejoin': 'round',
        'data-lucide': name
      };
      if (!hasA11y) svgAttrs['aria-hidden'] = 'true';
      for (var key in elAttrs) {
        if (key !== 'data-lucide') {
          svgAttrs[key] = elAttrs[key];
        }
      }
      var svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
      for (var key in svgAttrs) {
        svg.setAttribute(key, svgAttrs[key]);
      }
      for (var k = 0; k < icon.length; k++) {
        svg.appendChild(createSVGNode(icon[k]));
      }
      el.parentNode.replaceChild(svg, el);
    }
  };
})();
`;

fs.writeFileSync(path.join(distDir, 'icons.js'), output, 'utf-8');

const totalBytes = Object.entries(icons).reduce((acc, [, v]) => acc + JSON.stringify(v).length, 0);
console.log(`\u2713 dist/icons.js generated (${totalBytes}B icon data, ${Object.keys(icons).length} icons)`);
